### PR TITLE
Make the icon configurable

### PR DESCRIPTION
**Pull request by DidierA**
This adds an 'icon' entry in the config file where you can set the path to an icon file, or the name of a standard gtk icon (you can view standard icon names and the corresponding image with gtk3-icon-browser).

### CODE REVIEW

**Comment by Sispheor** [comment]
Hi, thanks for this PR.
Actually, changing the icon of an app is not really something we see a lot 😅
I would go for a fix of the current icon size. Maybe replacing it or finc a config that rezise it correctly.

**Comment by DidierA** [comment]
In my experience the icon was not resized so my top panel took about a quarter of the screen, so changing it to an svg file was the solution that made it for me. Given that the only purpoise if this icon is to be displayed next to the IP address, I thought it would make sense to make it possible for a user to change it.

**Comment by Sispheor** [comment]
Then wouldn't be better to just update the file to switch to a SVG version?

**Comment by Sispheor** [comment]
I close this one. 
I don't have the issue on Ubuntu 22.04

**Pull request closed without merging**
